# file: ./operations/checks/check-proper-access.yml
# 
# Checks both http://cawjpazlb/appA/ and http://cawjpazlb/appB/
#
# hard-coding the MDAE Lab for now

- name:  "Check#2 - Ingres URL check"
  hosts: cawjhub # we conly care that it can be accessed from outside 

  tasks:

  - name: Check connection to App A
    ansible.builtin.uri:
      url: http://cawjpazlb/appA/
    when: "'cawjpazlb' in group_names"

  - name: Check connection to App B
    ansible.builtin.uri:
      url: http://cawjpazlb/appB/    
