# file: ./operations/checks/check-proper-access.yml
# 
# Checks both http://cawjpazlb/appA/ and http://cawjpazlb/appB/
#
# hard-coding the MDAE Lab for now

- name:  "Check#2 - Ingres URL check"
  hosts: all # we conly care that it can be accessed from outside 

  tasks:

  - name: Check PAZLB ==> AppA
    ansible.builtin.uri:
      url: http://cawjpazlb/appA/
    when: "'cawjpazlb' in group_names"

  - name: Check PAZLB ==> AppB
    ansible.builtin.uri:
      url: http://cawjpazlb/appB/ 
    when: "'cawjpazlb' in group_names"

  - name: Check PAZLB ==> Proxy
    ansible.builtin.uri:
      url: http://{{ ansible_hostname }}/
    when: "'webservers' in group_names"
