# file: ./operations/checks/check-pazlb-proxy.yml
# 
#
# Does url checks for connectivity from the pazlb to all of the proxy servers
# 

- name:  "Check#X - PAZ LB ==> Proxy"
  hosts: cawjpazlb # we only want to check LB->Proxy
 

  tasks:
  
  - name: PAZ LB to proxy
    ansible.builtin.uri:
      url: http://cawjpazlb/appA/
    loop: "{{ groups['webservers'] }}" 
    ignore_errors: true

  - name: PAZ LB to proxy
    ansible.builtin.uri:
      url: http://cawjpazlb/appB/
    loop: "{{ groups['webservers'] }}"
    ignore_errors: true 
