---
# file: site.yml
#
# Main launch point for env install/setup
#

- name: Import common playbook
  ansible.builtin.import_playbook: infrastructure/common.yml

- name: Import Operations Zone
  ansible.builtin.import_playbook: infrastructure/ops.yml

- name: Import apps zone 
  ansible.builtin.import_playbook: infrastructure/apps.yml

- name: Import paz zone 
  ansible.builtin.import_playbook: infrastructure/paz.yml
