# file: ./operations/smoke-test/proxy-to-appslb
#
#
# Does url checks for connectivity from each proxy to the apps lb
#
# We also recheck to make sure each proxy can reach each app

- name:  "Check#4 - Proxy to APPS"
  hosts: webservers # we only want to check LB->Proxy
  gather_facts: false


  tasks:

  - name: Proxies to App A
    ansible.builtin.uri:
      url: http://cawjappslb/appA/
    ignore_errors: true

  - name: Proxies to App B
    ansible.builtin.uri:
      url: http://cawjappslb/appA/
    ignore_errors: true

  - name: Check if Apache is running
    command: systemctl status apache2
    ignore_errors: yes
    changed_when: false
    register: service_apache_status

  - name: Report status of Apache
    fail:
      msg: |
        Service apache2 is not running.
        Output of `systemctl status httpd`:
        {{ service_apache_status.stdout }}
        {{ service_apache_status.stderr }}
    when: service_apache_status | failed