---
# file: shutdown/apps-Red-Hat.yml
#
# Shuts down all the Linux services in the APPS Zone
# 

- name: Stop all Linux APPS Services
  hosts: apps

  tasks:

  - name: Populate service facts
    ansible.builtin.service_facts:

  # - name: Print service facts
  #   ansible.builtin.debug:
  #     var: ansible_facts.services
#
# Stop services from the most outside-in
#
#
# Start servics from the most inside-out
#

  - name: Stop Web Application Server (apache tomcat)
    become: true
    systemd:
      name: tomcat
      state: stopped
    when: "'tomcat.service' in services"