---
# file: operations/create-pazlb-cert.yml
#
# This playbook wil generate a self-siged cert for the pazlb
#

- name: Create PAZ LB Self-Sigend Cert
  hosts: cawjhub
  become: yes 

  tasks:

#
# Create local directory for cert storage
#
  - name: Creates directory
    ansible.builtin.file:
      path: "{{cert_repository}}""
      state: directory
      owner: root
      group: root
      mode: 0775

  # - name: Ensure private key is present
  #   community.crypto.openssl_privatekey:
  #     path: /etc/stunnel/redis-server.key
  #     size: 2048
  #     mode: "0600"
  #     type: RSA
    
  # - name: Ensure self-signed cert is present
  #   community.crypto.x509_certificate:
  #     path: /etc/stunnel/redis-server.crt
  #     privatekey_path: /etc/stunnel/redis-server.key
  #     provider: selfsigned
  #     selfsigned_not_after: "+3650d" # this is the default
  #     mode: "0644"