---
# file: operations/create-jks-keystore.yml
#
# This playbook wil generate a jks keystore
#

- name: Create JKS Keystore
  hosts: cawjhub
  become: yes 

  tasks:

#
# Create local directory for cert storage
#
  - name: Creates directory
    ansible.builtin.file:
      path: "{{cert_repository}}/jks"
      state: directory
      owner: ansiblead
      group: ansiblead
      mode: 0775
  
  - name: Create a key store for the given certificate (inline)
    community.general.java_keystore:
      name: example
      certificate: |
        -----BEGIN CERTIFICATE-----
        h19dUZ2co2fI/ibYiwxWk4aeNE6KWvCaTQOMQ8t6Uo2XKhpL/xnjoAgh1uCQN/69
        MG+34+RhUWzCfdZH7T8/qDxJw2kEPKluaYh7KnMsba+5jHjmtzix5QIDAQABo4IB
        -----END CERTIFICATE-----
      private_key: |
        -----BEGIN RSA PRIVATE KEY-----
        DBVFTEVDVFJJQ0lURSBERSBGUkFOQ0UxFzAVBgNVBAsMDjAwMDIgNTUyMDgxMzE3
        GLlDNMw/uHyME7gHFsqJA7O11VY6O5WQ4IDP3m/s5ZV6s+Nn6Lerz17VZ99
        -----END RSA PRIVATE KEY-----
      password: changeit
      dest: "{{cert_repository}}/jks/tmp_keystore.jks"

  # - name: Create a key store for the given certificate (lookup)
  #   community.general.java_keystore:
  #     name: example
  #     certificate: "{{lookup('file', '/path/to/certificate.crt') }}"
  #     private_key: "{{lookup('file', '/path/to/private.key') }}"
  #     password: changeit
  #     dest: /etc/security/keystore.jks