---
# file: operations/create-pazlb-cert.yml
#
# This playbook wil generate a self-siged cert for the pazlb
#

- name: Deploy PAZ Proxy certificate
  hosts: webservers
  become: true  

  vars:
    local_cert_repo: /etc/pki/tls

  tasks:

  - name: Copy public cert
    ansible.builtin.copy:
      src: "{{cert_repository}}/public/{{apache_ssl_cert_name}}.pem"
      dest: "{{local_cert_repo}}/certs/{{apache_ssl_cert_name}}.pem"
      owner: root
      group: root
      mode: '0644'
  
  - name: Copy private key
    ansible.builtin.copy:
      src: "{{cert_repository}}/private/{{apache_ssl_cert_name}}.key"
      dest: "{{local_cert_repo}}/private/{{apache_ssl_cert_name}}.key"
      owner: root
      group: root
      mode: '0644'