all:
  hosts:
    cawjcontrol:    # ansible control node
paz:                # PAZ Zone
  hosts: 
    cawjpazlb:      # paz load balancer
apps:               # App Zone
  hosts:
    cawjappslb:
webservers:
  hosts:
    cawjpazproxy1:
    cawjpazproxy2:
appservers:
  hosts:
    cawjappsA1:
    cawjappsA2:
    cawjappsB1:
    cawjappsB2:
dbservers:
  hosts:
    cawjopsDB1:
apiservers:
  hosts:  
    cawjopsAPI1:
devops:
  hosts:  
    cawjjevops:
  

