all:
  hosts:
    cawjcontrol:    # ansible control node
  children:
    windowsservers: 
      hosts: 
        cawjappsB1:
        cawjappsB2:
        cawjopsDB1:
        cawjopsAPI1:    
        
    linuxservers:
      hosts: 
        cawjcontrol: 
        cawjpazproxy1:
        cawjpazproxy2:
        cawjdevops:
        cawjappsA1:
        cawjappsA2:

    loadbalancers:
      hosts:
        cawjpazlb:
        cawjappslb:
        
paz:                # PAZ Zone
  hosts: 
    cawjpazlb:      # paz load balancer
  children:
    webservers:
      hosts:
        cawjpazproxy1:
        cawjpazproxy2:
        
apps:               # App Zone
  hosts:
    cawjappslb:
  children:
    appservers:
      hosts:
        cawjappsA1:
        cawjappsA2:
        cawjappsB1:
        cawjappsB2:
    appA:
      hosts:
        cawjappsA1:
        cawjappsA2:
    appB:
      hosts:
        cawjappsB1:
        cawjappsB2:
ops:
  children:
    dbservers:
      hosts:
        cawjopsDB1:
    apiservers:
      hosts:  
        cawjopsAPI1:
    devops:
      hosts:  
        cawjdevops:


