---
# file: common/push-host-map/tasks/main.yml
#
# Main task file to push host map
#
# The host map is stored in the host_ips vector, in vars/main.yml
#
# may not be needed for envs that have DNS
# TODO: doesn't need templates, but may need windows

- name: Add a line to a file
  ansible.builtin.lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
  with_items: "{{ host_ips }}"