---
#
# specify variables for template
#

# port http is running on
#
# simple change
lb_target_port: 80

# list of proxy hosts to balance
lb_target_list: 
  - cawjpazproxy1
  - cawjpazproxy2
  - blahblah
    
lb_zone: paz

lb_listen_port: 80
lb_listen_location: /
#lb_proxy_target: "http://backends/{{ lb_listen_location }}"
lb_proxy_target: "http://backends/"