---
# file: site_basic.yml
# 
# This playbook deploys, configures and updates the app server tier
#

# - name: Tomcat Install (windows install only)
#   ansible.builtin.import_playbook: ./apps/tomcat-windows.yml

- name: Tomcat Install (linux install only)
  ansible.builtin.import_playbook: ./apps/tomcat-linux.yml

- name: Load Balancer Install (apps install only)
  ansible.builtin.import_playbook: ./apps/loadbalancer-apps.yml


  
    
