---
# file: paz.yml
#
# Installs the PAZ zone proxy server
# LB at later date
#

- name: Running common tasks
  hosts: webservers

  roles: 

  - role: ../roles/paz/webserver-apache

  - role: ../roles/common/loadbalancer
    ngnix_conf_template: "templates/nginx.conf.j2"
    message: "Install paz loadbalancer"
