---
# file: site_basic.yml
# 
# This playbook deploys, configures and updates the app server tier
#

- name: Apache Proxy Install
  ansible.builtin.import_playbook: ./paz/tomcat-windows.yml

- name: Load Balancer Install (paz install only)
  ansible.builtin.import_playbook: ./paz/loadbalancer-apps.yml


  
    
