---
# file: paz.yml
#
# Installs the PAZ zone proxy server
# LB at later date
#

- name: Running common tasks
  hosts: webservers

  roles: 

  - role: ../roles/paz/webserver-apache

  - role: ../roles/paz/loadbalancer
    message: "Install paz loadbalancer"
